// <auto-generated />
using System;
using InfrStructure.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfraStructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241130075741_serviceExplanationChabged2")]
    partial class serviceExplanationChabged2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.ContractFinancialDetailes.ContractFinancialDetails", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Amount_of_timeExtension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Basis_of_Receipt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ContractID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContractInsurance_Percent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractTax_Percent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractValue_Added_Percent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoodJob_Percent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PercentageOfChanges")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ContractFinancialDetails", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.ContratTimeProfiles.ContractTimeProfile", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BasisForStartingProjectID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ContractDateOfNotification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ContractEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ContractExchangeDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ContractID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ContractPeriod")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ContractStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("BasisForStartingProjectID");

                    b.ToTable("ContractTimeProfiles", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.Contratcs.Contract", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConsultantID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsultantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ContractDateOfNotification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ContractEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ContractExchangeDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ContractExpertID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContractExpertName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ContractPeriod")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ContractStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContractTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ContractTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CorespondentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreditSourceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleteBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FinancialDetailsID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InsertContractBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InsertContractDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganizationUnitID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RequirementToCloseTheAccount")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoleOFOrganizationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TimeProfileID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TransActionTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("CreditSourceID");

                    b.HasIndex("FinancialDetailsID")
                        .IsUnique();

                    b.HasIndex("OrganizationUnitID");

                    b.HasIndex("TimeProfileID")
                        .IsUnique();

                    b.HasIndex("TransActionTypeID");

                    b.ToTable("Contracts", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.ServiceExplanations.ServiceExplanation", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AccelerationRate")
                        .HasColumnType("int");

                    b.Property<Guid>("ActivityCenterID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActivityReference")
                        .HasColumnType("int");

                    b.Property<Guid>("ContractID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrencyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeliverablePen")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExplanationEndingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExplanationStartingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExplanationType")
                        .HasColumnType("int");

                    b.Property<Guid>("FinePaymentMethodID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PrepaymentPercentage")
                        .HasColumnType("int");

                    b.Property<long?>("ProgramVolume")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ProjectID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProposalID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProposalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tilte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TotalAmount")
                        .HasColumnType("bigint");

                    b.Property<long>("UnitAmount")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("UnitOfMeasurementID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("ActivityCenterID");

                    b.HasIndex("ContractID");

                    b.HasIndex("CurrencyID");

                    b.HasIndex("FinePaymentMethodID");

                    b.HasIndex("UnitOfMeasurementID");

                    b.ToTable("ServiceExplanation", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.Errors.ErrorLogger", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FunctionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ErrorLogger", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.PriceListEntities.PriceListClauses.PriceListClause", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClauseTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PriceListFieldID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("PriceListFieldID");

                    b.ToTable("PriceListClause", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.PriceListEntities.PriceListExplanations.PriceListExplanation", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PriceListClauseID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RowNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitPrice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("PriceListClauseID");

                    b.ToTable("PriceListExplanation", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.PriceListEntities.PriceListFields.PriceListField", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FieldTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PriceListID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("PriceListID");

                    b.ToTable("PriceListField", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.PriceListEntities.PriceLists.PriceList", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PriceList", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.Activitycenters.Activitycenter", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Activitycenters", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.BasisForStartingTheProjects.BasisForStartingTheProject", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("BasisForStartingTheProject", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.BasisFortheEndOftheProjects.BasisFortheEndOftheProject", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("BasisFortheEndOftheProject", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.CorespondAndTypeOfCoopRel.CoresponedAndTypeCoopRels", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CoresponedLegalID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CoresponedRealID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TypeOfCoopreationID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("CoresponedLegalID");

                    b.HasIndex("CoresponedRealID");

                    b.HasIndex("TypeOfCoopreationID");

                    b.ToTable("CorespondAndTypeOfCoopRel", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.CorespondentLegals.CorespondentLegal", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankAcountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchCodeAndName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReal")
                        .HasColumnType("bit");

                    b.Property<string>("NationalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShabaNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CorespondentLegal", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.CorespondentReals.CorespondentReal", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankAcountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchCodeAndName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReal")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShabaNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CorespondentReal", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.CreditSources.CreditSource", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreditSourceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ParentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CreditSource", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.Currencies.Currency", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Currency", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.ExtensionTypes.ExtensionType", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ExtensionType", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.FinePaymentMethods.FinePaymentMethod", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("FinePaymentMethod", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.ForGuarantees.ForGuarantee", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ForGuarantee", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.HowToPays.HowToPay", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("HowToPay", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.Monetaryunits.Monetaryunit", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Monetaryunit", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.Organizationalunits.Organizationalunit", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Organizationalunit", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.ReasonForCancellations.ReasonForCancellation", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ReasonForCancellation", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.ReasonForTerminations.ReasonForTermination", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ReasonForTermination", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.ReleaseConditions.ReleaseCondition", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ReleaseCondition", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.TransActionTypes.TransActionType", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TransActionTypes", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.TypeOfCooperations.TypeOfCooperation", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TypeOfCooperation", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.UnitOfMeasurements.UnitOfMeasurement", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("UnitOfMeasurement", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.ContratTimeProfiles.ContractTimeProfile", b =>
                {
                    b.HasOne("AppCore.Entities.SettingEntities.BasisForStartingTheProjects.BasisForStartingTheProject", "BasisForStartingTheProject")
                        .WithMany("ContractTimeProfile")
                        .HasForeignKey("BasisForStartingProjectID");

                    b.Navigation("BasisForStartingTheProject");
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.Contratcs.Contract", b =>
                {
                    b.HasOne("AppCore.Entities.SettingEntities.CreditSources.CreditSource", "CreditSource")
                        .WithMany("Contract")
                        .HasForeignKey("CreditSourceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Entities.ContractsInformation.ContractFinancialDetailes.ContractFinancialDetails", "ContractFinancialDetails")
                        .WithOne("Contract")
                        .HasForeignKey("AppCore.Entities.ContractsInformation.Contratcs.Contract", "FinancialDetailsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Entities.SettingEntities.Organizationalunits.Organizationalunit", "Organizationalunit")
                        .WithMany("Contract")
                        .HasForeignKey("OrganizationUnitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Entities.ContractsInformation.ContratTimeProfiles.ContractTimeProfile", "ContratTimeProfile")
                        .WithOne("Contract")
                        .HasForeignKey("AppCore.Entities.ContractsInformation.Contratcs.Contract", "TimeProfileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Entities.SettingEntities.TransActionTypes.TransActionType", "TransActionType")
                        .WithMany("Contract")
                        .HasForeignKey("TransActionTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContractFinancialDetails");

                    b.Navigation("ContratTimeProfile");

                    b.Navigation("CreditSource");

                    b.Navigation("Organizationalunit");

                    b.Navigation("TransActionType");
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.ServiceExplanations.ServiceExplanation", b =>
                {
                    b.HasOne("AppCore.Entities.SettingEntities.Activitycenters.Activitycenter", "Activitycenter")
                        .WithMany("ServiceExplanation")
                        .HasForeignKey("ActivityCenterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Entities.ContractsInformation.Contratcs.Contract", "Contract")
                        .WithMany("ServiceExplanations")
                        .HasForeignKey("ContractID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Entities.SettingEntities.Currencies.Currency", "Currency")
                        .WithMany("ServiceExplanation")
                        .HasForeignKey("CurrencyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Entities.SettingEntities.FinePaymentMethods.FinePaymentMethod", "FinePaymentMethod")
                        .WithMany("ServiceExplanation")
                        .HasForeignKey("FinePaymentMethodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Entities.SettingEntities.UnitOfMeasurements.UnitOfMeasurement", "UnitOfMeasurement")
                        .WithMany("ServiceExplanation")
                        .HasForeignKey("UnitOfMeasurementID");

                    b.Navigation("Activitycenter");

                    b.Navigation("Contract");

                    b.Navigation("Currency");

                    b.Navigation("FinePaymentMethod");

                    b.Navigation("UnitOfMeasurement");
                });

            modelBuilder.Entity("AppCore.Entities.PriceListEntities.PriceListClauses.PriceListClause", b =>
                {
                    b.HasOne("AppCore.Entities.PriceListEntities.PriceListFields.PriceListField", "PriceListField")
                        .WithMany("PriceListClauses")
                        .HasForeignKey("PriceListFieldID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceListField");
                });

            modelBuilder.Entity("AppCore.Entities.PriceListEntities.PriceListExplanations.PriceListExplanation", b =>
                {
                    b.HasOne("AppCore.Entities.PriceListEntities.PriceListClauses.PriceListClause", "PriceListClause")
                        .WithMany("PriceListExplanations")
                        .HasForeignKey("PriceListClauseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceListClause");
                });

            modelBuilder.Entity("AppCore.Entities.PriceListEntities.PriceListFields.PriceListField", b =>
                {
                    b.HasOne("AppCore.Entities.PriceListEntities.PriceLists.PriceList", "PriceList")
                        .WithMany("PriceListFields")
                        .HasForeignKey("PriceListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceList");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.CorespondAndTypeOfCoopRel.CoresponedAndTypeCoopRels", b =>
                {
                    b.HasOne("AppCore.Entities.SettingEntities.CorespondentLegals.CorespondentLegal", null)
                        .WithMany("CorespondAndTypeOfCoopRels")
                        .HasForeignKey("CoresponedLegalID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AppCore.Entities.SettingEntities.CorespondentReals.CorespondentReal", null)
                        .WithMany("CorespondAndTypeOfCoopRels")
                        .HasForeignKey("CoresponedRealID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AppCore.Entities.SettingEntities.TypeOfCooperations.TypeOfCooperation", null)
                        .WithMany("CorespondAndTypeOfCoopRels")
                        .HasForeignKey("TypeOfCoopreationID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.ContractFinancialDetailes.ContractFinancialDetails", b =>
                {
                    b.Navigation("Contract")
                        .IsRequired();
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.ContratTimeProfiles.ContractTimeProfile", b =>
                {
                    b.Navigation("Contract")
                        .IsRequired();
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.Contratcs.Contract", b =>
                {
                    b.Navigation("ServiceExplanations");
                });

            modelBuilder.Entity("AppCore.Entities.PriceListEntities.PriceListClauses.PriceListClause", b =>
                {
                    b.Navigation("PriceListExplanations");
                });

            modelBuilder.Entity("AppCore.Entities.PriceListEntities.PriceListFields.PriceListField", b =>
                {
                    b.Navigation("PriceListClauses");
                });

            modelBuilder.Entity("AppCore.Entities.PriceListEntities.PriceLists.PriceList", b =>
                {
                    b.Navigation("PriceListFields");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.Activitycenters.Activitycenter", b =>
                {
                    b.Navigation("ServiceExplanation");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.BasisForStartingTheProjects.BasisForStartingTheProject", b =>
                {
                    b.Navigation("ContractTimeProfile");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.CorespondentLegals.CorespondentLegal", b =>
                {
                    b.Navigation("CorespondAndTypeOfCoopRels");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.CorespondentReals.CorespondentReal", b =>
                {
                    b.Navigation("CorespondAndTypeOfCoopRels");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.CreditSources.CreditSource", b =>
                {
                    b.Navigation("Contract");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.Currencies.Currency", b =>
                {
                    b.Navigation("ServiceExplanation");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.FinePaymentMethods.FinePaymentMethod", b =>
                {
                    b.Navigation("ServiceExplanation");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.Organizationalunits.Organizationalunit", b =>
                {
                    b.Navigation("Contract");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.TransActionTypes.TransActionType", b =>
                {
                    b.Navigation("Contract");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.TypeOfCooperations.TypeOfCooperation", b =>
                {
                    b.Navigation("CorespondAndTypeOfCoopRels");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.UnitOfMeasurements.UnitOfMeasurement", b =>
                {
                    b.Navigation("ServiceExplanation");
                });
#pragma warning restore 612, 618
        }
    }
}
