// <auto-generated />
using System;
using InfrStructure.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfraStructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241015142119_14030724-2")]
    partial class _140307242
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppCore.Entities.SettingEntities.Activitycenters.Activitycenter", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Activitycenters", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.BasisForStartingTheProjects.BasisForStartingTheProject", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("BasisForStartingTheProject", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.BasisFortheEndOftheProjects.BasisFortheEndOftheProject", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("BasisFortheEndOftheProject", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.CorespondAndTypeOfCoopRel.CoresponedAndTypeCoopRels", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CorespondentRealID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CoresponedLegalID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CoresponedRealID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TypeOfCooperationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TypeOfCoopreationID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("CorespondentRealID");

                    b.HasIndex("CoresponedLegalID");

                    b.HasIndex("CoresponedRealID");

                    b.HasIndex("TypeOfCooperationID");

                    b.HasIndex("TypeOfCoopreationID");

                    b.ToTable("CorespondAndTypeOfCoopRel", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.CorespondentLegals.CorespondentLegal", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankAcountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchCodeAndName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReal")
                        .HasColumnType("bit");

                    b.Property<string>("NationalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShabaNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CorespondentLegal", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.CorespondentReals.CorespondentReal", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankAcountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchCodeAndName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReal")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShabaNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CorespondentReal", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.CreditSources.CreditSource", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreditSourceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CreditSource", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.ExtensionTypes.ExtensionType", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ExtensionType", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.FinePaymentMethods.FinePaymentMethod", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("FinePaymentMethod", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.ForGuarantees.ForGuarantee", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ForGuarantee", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.HowToPays.HowToPay", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("HowToPay", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.Monetaryunits.Monetaryunit", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Monetaryunit", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.Organizationalunits.Organizationalunit", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Organizationalunit", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.ReasonForCancellations.ReasonForCancellation", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ReasonForCancellation", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.ReasonForTerminations.ReasonForTermination", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ReasonForTermination", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.ReleaseConditions.ReleaseCondition", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ReleaseCondition", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.TransActionTypes.TransActionType", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TransActionTypes", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.TypeOfCooperations.TypeOfCooperation", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TypeOfCooperation", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.CorespondAndTypeOfCoopRel.CoresponedAndTypeCoopRels", b =>
                {
                    b.HasOne("AppCore.Entities.SettingEntities.CorespondentReals.CorespondentReal", null)
                        .WithMany("CorespondAndTypeOfCoopRels")
                        .HasForeignKey("CorespondentRealID");

                    b.HasOne("AppCore.Entities.SettingEntities.CorespondentLegals.CorespondentLegal", null)
                        .WithMany("CorespondAndTypeOfCoopRels")
                        .HasForeignKey("CoresponedLegalID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AppCore.Entities.SettingEntities.CorespondentReals.CorespondentReal", null)
                        .WithMany()
                        .HasForeignKey("CoresponedRealID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AppCore.Entities.SettingEntities.TypeOfCooperations.TypeOfCooperation", null)
                        .WithMany("CorespondAndTypeOfCoopRels")
                        .HasForeignKey("TypeOfCooperationID");

                    b.HasOne("AppCore.Entities.SettingEntities.TypeOfCooperations.TypeOfCooperation", null)
                        .WithMany()
                        .HasForeignKey("TypeOfCoopreationID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.CorespondentLegals.CorespondentLegal", b =>
                {
                    b.Navigation("CorespondAndTypeOfCoopRels");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.CorespondentReals.CorespondentReal", b =>
                {
                    b.Navigation("CorespondAndTypeOfCoopRels");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.TypeOfCooperations.TypeOfCooperation", b =>
                {
                    b.Navigation("CorespondAndTypeOfCoopRels");
                });
#pragma warning restore 612, 618
        }
    }
}
