// <auto-generated />
using System;
using InfrStructure.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfraStructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250203071023_add_RoleOfOrganization")]
    partial class add_RoleOfOrganization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppCore.Entities.Attaches.Attach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileExtention")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadeDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserUploader")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("Attach", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.ContractAddendums.ContractAddendum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AddendumChangeType")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddendumDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AddendumTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteAddenDumDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeleteAddendumBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InsertAddendumBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InsertAddendumDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RateOfContractPriceChanged")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddendumTypeId");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractAddendums", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.ContractCheckListValues.ContractCheckListValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CheckListValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ContractId")
                        .IsUnique();

                    b.ToTable("ContractCheckListValues", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.ContractCoefficients.ContractCoefficient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddendumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("CoefficientValue")
                        .HasColumnType("Decimal(10,5)");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DefaultRowValue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsAddendum")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("UpdatedInAddendum")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AddendumId");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractCoefficients", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.ContractEstimatedmeters.ContractEstimatedmeter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityCenter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ActivityCenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddendumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("Decimal(30,5)");

                    b.Property<string>("Clause")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ClauseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoefficientTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ContractAddendumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Explenation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ExplenationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsAddendum")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("RawPrice")
                        .HasColumnType("Decimal(30,5)");

                    b.Property<decimal>("RowPrice")
                        .HasColumnType("Decimal(30,5)");

                    b.Property<Guid>("ServiceExplanationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SumOfCoefficients")
                        .HasColumnType("Decimal(10,5)");

                    b.Property<DateTime?>("UpdateInAddendumDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("UpdatedInAddendum")
                        .HasColumnType("bit");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("YearId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClauseId");

                    b.HasIndex("ContractAddendumId");

                    b.HasIndex("ExplenationId");

                    b.HasIndex("FieldId");

                    b.HasIndex("ServiceExplanationId");

                    b.HasIndex("YearId");

                    b.ToTable("ContractEstimatedmeters", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.ContractFinancialDetailes.ContractFinancialDetails", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Amount_of_timeExtension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Basis_of_Receipt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ContractID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ContractInsurance_Percent")
                        .HasColumnType("Decimal(7,5)");

                    b.Property<decimal>("ContractTax_Percent")
                        .HasColumnType("Decimal(7,5)");

                    b.Property<decimal>("ContractValue_Added_Percent")
                        .HasColumnType("Decimal(7,5)");

                    b.Property<decimal>("GoodJob_Percent")
                        .HasColumnType("Decimal(7,5)");

                    b.Property<decimal?>("PercentageOfChanges")
                        .HasColumnType("Decimal(7,5)");

                    b.HasKey("ID");

                    b.ToTable("ContractFinancialDetails", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.ContractGuarantees.ContractGuarantee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ForGuaranteeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GuaranteePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RealeaseDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RealeaseExplenation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReleaseConditionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TypeOfGuaranteeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ValidityDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("ForGuaranteeId");

                    b.HasIndex("ReleaseConditionId");

                    b.HasIndex("TypeOfGuaranteeId");

                    b.ToTable("ContractGuarantees", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.ContratTimeProfiles.ContractTimeProfile", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BasisForStartingProjectID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ContractDateOfNotification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ContractEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ContractExchangeDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ContractID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContractPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ContractStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("BasisForStartingProjectID");

                    b.ToTable("ContractTimeProfiles", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.Contratcs.Contract", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConsultantID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsultantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ContractCheckListValueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ContractDateOfNotification")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ContractEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ContractExchangeDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ContractExpertID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContractExpertName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ContractPeriod")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ContractStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContractTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ContractTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CorespondentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CorespondentRealOrLegal")
                        .HasColumnType("bit");

                    b.Property<Guid>("CreditSourceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleteBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FinancialDetailsID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("HasAddendum")
                        .HasColumnType("bit");

                    b.Property<Guid>("InsertContractBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InsertContractDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganizationUnitID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RequirementToCloseTheAccount")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoleOFOrganizationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TimeProfileID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TransActionTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("ContractTypeID");

                    b.HasIndex("CreditSourceID");

                    b.HasIndex("FinancialDetailsID")
                        .IsUnique();

                    b.HasIndex("OrganizationUnitID");

                    b.HasIndex("TimeProfileID")
                        .IsUnique();

                    b.HasIndex("TransActionTypeID");

                    b.ToTable("Contracts", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.ServiceExplanations.ServiceExplanation", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AccelerationRate")
                        .HasColumnType("Decimal(30,5)");

                    b.Property<Guid>("ActivityCenterID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActivityReference")
                        .HasColumnType("int");

                    b.Property<Guid?>("ContractAddendumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContractID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrencyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedInAddedumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeliverablePen")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExplanationEndingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExplanationStartingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExplanationType")
                        .HasColumnType("int");

                    b.Property<Guid?>("FinePaymentMethodID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAddendum")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("Order")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PrepaymentPercentage")
                        .HasColumnType("Decimal(7,5)");

                    b.Property<decimal?>("ProgramVolume")
                        .HasColumnType("Decimal(30,5)");

                    b.Property<Guid?>("ProjectID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProposalID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProposalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("Decimal(30,5)");

                    b.Property<decimal?>("UnitAmount")
                        .HasColumnType("Decimal(30,5)");

                    b.Property<Guid?>("UnitOfMeasurementID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdateInAddendumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("UpdatedInAddendum")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("ActivityCenterID");

                    b.HasIndex("ContractAddendumId");

                    b.HasIndex("ContractID");

                    b.HasIndex("CurrencyID");

                    b.HasIndex("FinePaymentMethodID");

                    b.ToTable("ServiceExplanation", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.Errors.ErrorLogger", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FunctionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ErrorLogger", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.InvoiceInformations.EstimatedMeterFinancials.EstimatedMeterFinancial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ApprovedPercent")
                        .HasColumnType("decimal(7, 5)");

                    b.Property<decimal>("ApprovedPrice")
                        .HasColumnType("decimal(30, 5)");

                    b.Property<decimal?>("ApprovedVolume")
                        .HasColumnType("decimal(30, 5)");

                    b.Property<Guid>("ContractEstimatedmeterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InvoiceBaseInformationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("RequestedPercent")
                        .HasColumnType("decimal(7, 5)");

                    b.Property<decimal>("RequestedPrice")
                        .HasColumnType("decimal(30, 5)");

                    b.Property<decimal?>("RequestedVolume")
                        .HasColumnType("decimal(30, 5)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceBaseInformationId");

                    b.ToTable("EstimatedMeterFinancials", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.InvoiceInformations.InvoiceBaseInformations.InvoiceBaseInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeleteBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("InsertBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("InvoiceNumber")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceTitle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("InvoiceTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LeadingToDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("InvoiceTypeId");

                    b.ToTable("InvoiceBaseInformations", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.InvoiceInformations.NettingProcesses.NettingProcessItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(30, 5)");

                    b.Property<Guid>("DeleteBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InsertBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InvoiceBaseInformationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeduction")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(7, 5)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceBaseInformationId");

                    b.ToTable("NettingProcessItems", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.InvoiceInformations.ServiceExplanationFinancials.ServiceExplanationFinancial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ApprovedPercent")
                        .HasColumnType("decimal(7, 5)");

                    b.Property<decimal>("ApprovedPrice")
                        .HasColumnType("decimal(30, 5)");

                    b.Property<decimal?>("ApprovedVolume")
                        .HasColumnType("decimal(30, 5)");

                    b.Property<Guid>("InvoiceBaseInformationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("RequestedPercent")
                        .HasColumnType("decimal(7, 5)");

                    b.Property<decimal>("RequestedPrice")
                        .HasColumnType("decimal(30, 5)");

                    b.Property<decimal?>("RequestedVolume")
                        .HasColumnType("decimal(30, 5)");

                    b.Property<Guid>("ServiceExplanationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceBaseInformationId");

                    b.ToTable("ServiceExplanationFinancials", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.InvoicesInformations.InvoiceType.InvoiceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InvoiceTypes", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.PriceListEntities.PriceListClauses.PriceListClause", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClauseTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PriceListFieldID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("PriceListFieldID");

                    b.ToTable("PriceListClause", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.PriceListEntities.PriceListExplanations.PriceListExplanation", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsStar")
                        .HasColumnType("bit");

                    b.Property<Guid>("PriceListClauseID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RowNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitPrice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("PriceListClauseID");

                    b.ToTable("PriceListExplanation", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.PriceListEntities.PriceListFields.PriceListField", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FieldTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PriceListID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("PriceListID");

                    b.ToTable("PriceListField", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.PriceListEntities.PriceLists.PriceList", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PriceList", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.Activitycenters.Activitycenter", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Activitycenters", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.AddendumTypes.AddendumType", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AddendumChangeType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("AddendumTypes", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.BasisForStartingTheProjects.BasisForStartingTheProject", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("BasisForStartingTheProject", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.BasisFortheEndOftheProjects.BasisFortheEndOftheProject", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("BasisFortheEndOftheProject", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.CheckLists.CheckList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContractTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LookUpTableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ContractTypeId");

                    b.HasIndex("LookUpTableId");

                    b.ToTable("CheckLists", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.ContractTypes.ContractType", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ContractTypes", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.CorespondAndTypeOfCoopRel.CorespondRealAndTypeOfCoopRel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CorespondentRealID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TypeOfCooperationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TypeOfCoopreationID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("CorespondentRealID");

                    b.HasIndex("TypeOfCooperationID");

                    b.ToTable("CorespondRealAntTypeOfCoopRel", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.CorespondAndTypeOfCoopRel.CoresponedAndTypeCoopRels", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CoresponedLegalID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TypeOfCoopreationID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("CoresponedLegalID");

                    b.HasIndex("TypeOfCoopreationID");

                    b.ToTable("CorespondAndTypeOfCoopRel", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.CorespondentLegals.CorespondentLegal", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankAcountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchCodeAndName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountyId")
                        .HasColumnType("int");

                    b.Property<string>("EconomicCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReal")
                        .HasColumnType("bit");

                    b.Property<string>("NationalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProvincId")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShabaNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CityId");

                    b.HasIndex("CountyId");

                    b.HasIndex("ProvincId");

                    b.ToTable("CorespondentLegal", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.CorespondentReals.CorespondentReal", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankAcountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchCodeAndName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificateNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<int?>("CountyId")
                        .HasColumnType("int");

                    b.Property<string>("EconomicCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReal")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProvincId")
                        .HasColumnType("int");

                    b.Property<string>("ShabaNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CityId");

                    b.HasIndex("CountyId");

                    b.HasIndex("ProvincId");

                    b.ToTable("CorespondentReal", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.CreditSources.CreditSource", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreditSourceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CreditSource", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.Currencies.Currency", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EnglishTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Currency", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.DefaultCoefficients.DefaultCoefficients", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("DefaultCoefficient")
                        .HasColumnType("Decimal(30,5)");

                    b.Property<string>("DefaultRows")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("DefaultCoefficients", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.ExtensionTypes.ExtensionType", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ExtensionType", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.FinePaymentMethods.FinePaymentMethod", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("FinePaymentMethod", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.ForGuarantees.ForGuarantee", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ForGuarantee", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.HowToPays.HowToPay", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("HowToPay", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.Locations.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountyId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("City", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.Locations.County", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("County", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.Locations.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Province", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.LookUpTables.LookUpTable", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ID");

                    b.ToTable("LookUpTables", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.LookUpTables.LookUpTableInside", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LookUpTableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ID");

                    b.HasIndex("LookUpTableId");

                    b.ToTable("LookUpTableInsides", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.Monetaryunits.Monetaryunit", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Monetaryunit", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.Organizationalunits.Organizationalunit", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Organizationalunit", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.PaymentMethods.PaymentMethod", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PaymentMethods", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.ReasonForCancellations.ReasonForCancellation", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ReasonForCancellation", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.ReasonForTerminations.ReasonForTermination", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ReasonForTermination", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.ReleaseConditions.ReleaseCondition", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ReleaseCondition", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.RoleOfOrganizations.RoleOfOrganization", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ID");

                    b.ToTable("RoleOfOrganizations", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.Roles.Role", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Roles", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.StagesRoles.StagesRoles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("StagesRoles", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.TransActionTypes.TransActionType", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TransActionTypes", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.TypeOfCooperations.TypeOfCooperation", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TypeOfCooperation", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.TypeOfGuarantees.TypeOfGuarantee", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TypeOfGuarantees", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.UnitOfMeasurements.UnitOfMeasurement", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("UnitOfMeasurement", "TAM");
                });

            modelBuilder.Entity("AppCore.Entities.Attaches.Attach", b =>
                {
                    b.HasOne("AppCore.Entities.ContractsInformation.Contratcs.Contract", "Contract")
                        .WithMany("Attaches")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.ContractAddendums.ContractAddendum", b =>
                {
                    b.HasOne("AppCore.Entities.SettingEntities.AddendumTypes.AddendumType", "AddendumType")
                        .WithMany("ContractAddendum")
                        .HasForeignKey("AddendumTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AppCore.Entities.ContractsInformation.Contratcs.Contract", "Contract")
                        .WithMany("ContractAddendums")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AddendumType");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.ContractCheckListValues.ContractCheckListValue", b =>
                {
                    b.HasOne("AppCore.Entities.ContractsInformation.Contratcs.Contract", "Contract")
                        .WithOne("ContractCheckListValues")
                        .HasForeignKey("AppCore.Entities.ContractsInformation.ContractCheckListValues.ContractCheckListValue", "ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.ContractCoefficients.ContractCoefficient", b =>
                {
                    b.HasOne("AppCore.Entities.ContractsInformation.ContractAddendums.ContractAddendum", "ContractAddendum")
                        .WithMany("ContractCoefficients")
                        .HasForeignKey("AddendumId");

                    b.HasOne("AppCore.Entities.ContractsInformation.Contratcs.Contract", "Contract")
                        .WithMany("ContractCoefficients")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("ContractAddendum");
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.ContractEstimatedmeters.ContractEstimatedmeter", b =>
                {
                    b.HasOne("AppCore.Entities.PriceListEntities.PriceListClauses.PriceListClause", "PriceListClause")
                        .WithMany("ContractEstimatedmeters")
                        .HasForeignKey("ClauseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AppCore.Entities.ContractsInformation.ContractAddendums.ContractAddendum", "ContractAddendum")
                        .WithMany("ContractEstimatedmeters")
                        .HasForeignKey("ContractAddendumId");

                    b.HasOne("AppCore.Entities.PriceListEntities.PriceListExplanations.PriceListExplanation", "PriceListExplanation")
                        .WithMany("ContractEstimatedmeters")
                        .HasForeignKey("ExplenationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AppCore.Entities.PriceListEntities.PriceListFields.PriceListField", "PriceListField")
                        .WithMany("ContractEstimatedmeters")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AppCore.Entities.ContractsInformation.ServiceExplanations.ServiceExplanation", "ServiceExplanation")
                        .WithMany("ContractEstimatedmeters")
                        .HasForeignKey("ServiceExplanationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Entities.PriceListEntities.PriceLists.PriceList", "PriceList")
                        .WithMany("ContractEstimatedmeters")
                        .HasForeignKey("YearId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ContractAddendum");

                    b.Navigation("PriceList");

                    b.Navigation("PriceListClause");

                    b.Navigation("PriceListExplanation");

                    b.Navigation("PriceListField");

                    b.Navigation("ServiceExplanation");
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.ContractGuarantees.ContractGuarantee", b =>
                {
                    b.HasOne("AppCore.Entities.ContractsInformation.Contratcs.Contract", "Contract")
                        .WithMany("ContractGuarantees")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Entities.SettingEntities.ForGuarantees.ForGuarantee", "ForGuarantee")
                        .WithMany("ContractGuarantees")
                        .HasForeignKey("ForGuaranteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Entities.SettingEntities.ReleaseConditions.ReleaseCondition", "ReleaseCondition")
                        .WithMany("ContractGuarantees")
                        .HasForeignKey("ReleaseConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Entities.SettingEntities.TypeOfGuarantees.TypeOfGuarantee", "TypeOfGuarantee")
                        .WithMany("ContractGuarantees")
                        .HasForeignKey("TypeOfGuaranteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("ForGuarantee");

                    b.Navigation("ReleaseCondition");

                    b.Navigation("TypeOfGuarantee");
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.ContratTimeProfiles.ContractTimeProfile", b =>
                {
                    b.HasOne("AppCore.Entities.SettingEntities.BasisForStartingTheProjects.BasisForStartingTheProject", "BasisForStartingTheProject")
                        .WithMany("ContractTimeProfile")
                        .HasForeignKey("BasisForStartingProjectID");

                    b.Navigation("BasisForStartingTheProject");
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.Contratcs.Contract", b =>
                {
                    b.HasOne("AppCore.Entities.SettingEntities.ContractTypes.ContractType", "ContractType")
                        .WithMany("Contracts")
                        .HasForeignKey("ContractTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Entities.SettingEntities.CreditSources.CreditSource", "CreditSource")
                        .WithMany("Contract")
                        .HasForeignKey("CreditSourceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Entities.ContractsInformation.ContractFinancialDetailes.ContractFinancialDetails", "ContractFinancialDetails")
                        .WithOne("Contract")
                        .HasForeignKey("AppCore.Entities.ContractsInformation.Contratcs.Contract", "FinancialDetailsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Entities.SettingEntities.Organizationalunits.Organizationalunit", "Organizationalunit")
                        .WithMany("Contract")
                        .HasForeignKey("OrganizationUnitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Entities.ContractsInformation.ContratTimeProfiles.ContractTimeProfile", "ContratTimeProfile")
                        .WithOne("Contract")
                        .HasForeignKey("AppCore.Entities.ContractsInformation.Contratcs.Contract", "TimeProfileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Entities.SettingEntities.TransActionTypes.TransActionType", "TransActionType")
                        .WithMany("Contract")
                        .HasForeignKey("TransActionTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContractFinancialDetails");

                    b.Navigation("ContractType");

                    b.Navigation("ContratTimeProfile");

                    b.Navigation("CreditSource");

                    b.Navigation("Organizationalunit");

                    b.Navigation("TransActionType");
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.ServiceExplanations.ServiceExplanation", b =>
                {
                    b.HasOne("AppCore.Entities.SettingEntities.Activitycenters.Activitycenter", "Activitycenter")
                        .WithMany("ServiceExplanation")
                        .HasForeignKey("ActivityCenterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Entities.ContractsInformation.ContractAddendums.ContractAddendum", "ContractAddendum")
                        .WithMany("ServiceExplanations")
                        .HasForeignKey("ContractAddendumId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AppCore.Entities.ContractsInformation.Contratcs.Contract", "Contract")
                        .WithMany("ServiceExplanations")
                        .HasForeignKey("ContractID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Entities.SettingEntities.Currencies.Currency", "Currency")
                        .WithMany("ServiceExplanation")
                        .HasForeignKey("CurrencyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Entities.SettingEntities.FinePaymentMethods.FinePaymentMethod", "FinePaymentMethod")
                        .WithMany("ServiceExplanation")
                        .HasForeignKey("FinePaymentMethodID");

                    b.Navigation("Activitycenter");

                    b.Navigation("Contract");

                    b.Navigation("ContractAddendum");

                    b.Navigation("Currency");

                    b.Navigation("FinePaymentMethod");
                });

            modelBuilder.Entity("AppCore.Entities.InvoiceInformations.EstimatedMeterFinancials.EstimatedMeterFinancial", b =>
                {
                    b.HasOne("AppCore.Entities.InvoiceInformations.InvoiceBaseInformations.InvoiceBaseInformation", "InvoiceBaseInformation")
                        .WithMany("EstimatedMeterFinancials")
                        .HasForeignKey("InvoiceBaseInformationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InvoiceBaseInformation");
                });

            modelBuilder.Entity("AppCore.Entities.InvoiceInformations.InvoiceBaseInformations.InvoiceBaseInformation", b =>
                {
                    b.HasOne("AppCore.Entities.ContractsInformation.Contratcs.Contract", "Contract")
                        .WithMany("InvoiceBaseInformations")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AppCore.Entities.InvoicesInformations.InvoiceType.InvoiceType", "InvoiceType")
                        .WithMany()
                        .HasForeignKey("InvoiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("InvoiceType");
                });

            modelBuilder.Entity("AppCore.Entities.InvoiceInformations.NettingProcesses.NettingProcessItem", b =>
                {
                    b.HasOne("AppCore.Entities.InvoiceInformations.InvoiceBaseInformations.InvoiceBaseInformation", "InvoiceBaseInformation")
                        .WithMany("NettingProcessItems")
                        .HasForeignKey("InvoiceBaseInformationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InvoiceBaseInformation");
                });

            modelBuilder.Entity("AppCore.Entities.InvoiceInformations.ServiceExplanationFinancials.ServiceExplanationFinancial", b =>
                {
                    b.HasOne("AppCore.Entities.InvoiceInformations.InvoiceBaseInformations.InvoiceBaseInformation", "InvoiceBaseInformation")
                        .WithMany("ServiceExplanationFinancials")
                        .HasForeignKey("InvoiceBaseInformationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InvoiceBaseInformation");
                });

            modelBuilder.Entity("AppCore.Entities.PriceListEntities.PriceListClauses.PriceListClause", b =>
                {
                    b.HasOne("AppCore.Entities.PriceListEntities.PriceListFields.PriceListField", "PriceListField")
                        .WithMany("PriceListClauses")
                        .HasForeignKey("PriceListFieldID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceListField");
                });

            modelBuilder.Entity("AppCore.Entities.PriceListEntities.PriceListExplanations.PriceListExplanation", b =>
                {
                    b.HasOne("AppCore.Entities.PriceListEntities.PriceListClauses.PriceListClause", "PriceListClause")
                        .WithMany("PriceListExplanations")
                        .HasForeignKey("PriceListClauseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceListClause");
                });

            modelBuilder.Entity("AppCore.Entities.PriceListEntities.PriceListFields.PriceListField", b =>
                {
                    b.HasOne("AppCore.Entities.PriceListEntities.PriceLists.PriceList", "PriceList")
                        .WithMany("PriceListFields")
                        .HasForeignKey("PriceListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceList");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.CheckLists.CheckList", b =>
                {
                    b.HasOne("AppCore.Entities.SettingEntities.ContractTypes.ContractType", "ContractType")
                        .WithMany("CheckLists")
                        .HasForeignKey("ContractTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Entities.SettingEntities.LookUpTables.LookUpTable", "LookUpTable")
                        .WithMany("CheckLists")
                        .HasForeignKey("LookUpTableId");

                    b.Navigation("ContractType");

                    b.Navigation("LookUpTable");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.CorespondAndTypeOfCoopRel.CorespondRealAndTypeOfCoopRel", b =>
                {
                    b.HasOne("AppCore.Entities.SettingEntities.CorespondentReals.CorespondentReal", null)
                        .WithMany("CorespondAndTypeOfCoopRels")
                        .HasForeignKey("CorespondentRealID");

                    b.HasOne("AppCore.Entities.SettingEntities.TypeOfCooperations.TypeOfCooperation", null)
                        .WithMany("CorespondRealAndTypeOfCoopRels")
                        .HasForeignKey("TypeOfCooperationID");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.CorespondAndTypeOfCoopRel.CoresponedAndTypeCoopRels", b =>
                {
                    b.HasOne("AppCore.Entities.SettingEntities.CorespondentLegals.CorespondentLegal", null)
                        .WithMany("CorespondAndTypeOfCoopRels")
                        .HasForeignKey("CoresponedLegalID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AppCore.Entities.SettingEntities.TypeOfCooperations.TypeOfCooperation", null)
                        .WithMany("CorespondAndTypeOfCoopRels")
                        .HasForeignKey("TypeOfCoopreationID")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.CorespondentLegals.CorespondentLegal", b =>
                {
                    b.HasOne("AppCore.Entities.SettingEntities.Locations.City", "City")
                        .WithMany("CorespondentLegal")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AppCore.Entities.SettingEntities.Locations.County", "County")
                        .WithMany("CorespondentLegal")
                        .HasForeignKey("CountyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AppCore.Entities.SettingEntities.Locations.Province", "Province")
                        .WithMany("CorespondentLegal")
                        .HasForeignKey("ProvincId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("City");

                    b.Navigation("County");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.CorespondentReals.CorespondentReal", b =>
                {
                    b.HasOne("AppCore.Entities.SettingEntities.Locations.City", "City")
                        .WithMany("CorespondentReals")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AppCore.Entities.SettingEntities.Locations.County", "County")
                        .WithMany("CorespondentReals")
                        .HasForeignKey("CountyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AppCore.Entities.SettingEntities.Locations.Province", "Province")
                        .WithMany("CorespondentReals")
                        .HasForeignKey("ProvincId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("City");

                    b.Navigation("County");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.Locations.City", b =>
                {
                    b.HasOne("AppCore.Entities.SettingEntities.Locations.County", "County")
                        .WithMany("Cities")
                        .HasForeignKey("CountyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Entities.SettingEntities.Locations.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("County");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.Locations.County", b =>
                {
                    b.HasOne("AppCore.Entities.SettingEntities.Locations.Province", "Province")
                        .WithMany("County")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.LookUpTables.LookUpTableInside", b =>
                {
                    b.HasOne("AppCore.Entities.SettingEntities.LookUpTables.LookUpTable", "LookUpTable")
                        .WithMany("LookUpTableInsides")
                        .HasForeignKey("LookUpTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LookUpTable");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.StagesRoles.StagesRoles", b =>
                {
                    b.HasOne("AppCore.Entities.SettingEntities.Roles.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.ContractAddendums.ContractAddendum", b =>
                {
                    b.Navigation("ContractCoefficients");

                    b.Navigation("ContractEstimatedmeters");

                    b.Navigation("ServiceExplanations");
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.ContractFinancialDetailes.ContractFinancialDetails", b =>
                {
                    b.Navigation("Contract")
                        .IsRequired();
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.ContratTimeProfiles.ContractTimeProfile", b =>
                {
                    b.Navigation("Contract")
                        .IsRequired();
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.Contratcs.Contract", b =>
                {
                    b.Navigation("Attaches");

                    b.Navigation("ContractAddendums");

                    b.Navigation("ContractCheckListValues");

                    b.Navigation("ContractCoefficients");

                    b.Navigation("ContractGuarantees");

                    b.Navigation("InvoiceBaseInformations");

                    b.Navigation("ServiceExplanations");
                });

            modelBuilder.Entity("AppCore.Entities.ContractsInformation.ServiceExplanations.ServiceExplanation", b =>
                {
                    b.Navigation("ContractEstimatedmeters");
                });

            modelBuilder.Entity("AppCore.Entities.InvoiceInformations.InvoiceBaseInformations.InvoiceBaseInformation", b =>
                {
                    b.Navigation("EstimatedMeterFinancials");

                    b.Navigation("NettingProcessItems");

                    b.Navigation("ServiceExplanationFinancials");
                });

            modelBuilder.Entity("AppCore.Entities.PriceListEntities.PriceListClauses.PriceListClause", b =>
                {
                    b.Navigation("ContractEstimatedmeters");

                    b.Navigation("PriceListExplanations");
                });

            modelBuilder.Entity("AppCore.Entities.PriceListEntities.PriceListExplanations.PriceListExplanation", b =>
                {
                    b.Navigation("ContractEstimatedmeters");
                });

            modelBuilder.Entity("AppCore.Entities.PriceListEntities.PriceListFields.PriceListField", b =>
                {
                    b.Navigation("ContractEstimatedmeters");

                    b.Navigation("PriceListClauses");
                });

            modelBuilder.Entity("AppCore.Entities.PriceListEntities.PriceLists.PriceList", b =>
                {
                    b.Navigation("ContractEstimatedmeters");

                    b.Navigation("PriceListFields");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.Activitycenters.Activitycenter", b =>
                {
                    b.Navigation("ServiceExplanation");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.AddendumTypes.AddendumType", b =>
                {
                    b.Navigation("ContractAddendum");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.BasisForStartingTheProjects.BasisForStartingTheProject", b =>
                {
                    b.Navigation("ContractTimeProfile");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.ContractTypes.ContractType", b =>
                {
                    b.Navigation("CheckLists");

                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.CorespondentLegals.CorespondentLegal", b =>
                {
                    b.Navigation("CorespondAndTypeOfCoopRels");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.CorespondentReals.CorespondentReal", b =>
                {
                    b.Navigation("CorespondAndTypeOfCoopRels");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.CreditSources.CreditSource", b =>
                {
                    b.Navigation("Contract");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.Currencies.Currency", b =>
                {
                    b.Navigation("ServiceExplanation");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.FinePaymentMethods.FinePaymentMethod", b =>
                {
                    b.Navigation("ServiceExplanation");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.ForGuarantees.ForGuarantee", b =>
                {
                    b.Navigation("ContractGuarantees");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.Locations.City", b =>
                {
                    b.Navigation("CorespondentLegal");

                    b.Navigation("CorespondentReals");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.Locations.County", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("CorespondentLegal");

                    b.Navigation("CorespondentReals");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.Locations.Province", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("CorespondentLegal");

                    b.Navigation("CorespondentReals");

                    b.Navigation("County");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.LookUpTables.LookUpTable", b =>
                {
                    b.Navigation("CheckLists");

                    b.Navigation("LookUpTableInsides");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.Organizationalunits.Organizationalunit", b =>
                {
                    b.Navigation("Contract");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.ReleaseConditions.ReleaseCondition", b =>
                {
                    b.Navigation("ContractGuarantees");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.TransActionTypes.TransActionType", b =>
                {
                    b.Navigation("Contract");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.TypeOfCooperations.TypeOfCooperation", b =>
                {
                    b.Navigation("CorespondAndTypeOfCoopRels");

                    b.Navigation("CorespondRealAndTypeOfCoopRels");
                });

            modelBuilder.Entity("AppCore.Entities.SettingEntities.TypeOfGuarantees.TypeOfGuarantee", b =>
                {
                    b.Navigation("ContractGuarantees");
                });
#pragma warning restore 612, 618
        }
    }
}
